CREATE TABLE [SpellDto] (
	[Id] INT IDENTITY(1, 1) NOT NULL,
	[Name] VARCHAR(75),
	Duration VARCHAR(100),
	School VARCHAR(50),
	Subschool VARCHAR(50),
	Effect VARCHAR(250),
	EffectType VARCHAR(50),
	SpellType VARCHAR(50),
	CastingTime VARCHAR(50),
	Components VARCHAR(350),
	[Range] VARCHAR(50),
	Area VARCHAR(150),
	Targets VARCHAR(188),
	SavingThrow VARCHAR(50),
	Harmless BIT NOT NULL,
	Resistance BIT NOT NULL,
	[Description] VARCHAR(Max),
	[Source] VARCHAR(50),
	CostlyComponents BIT NOT NULL,
	Dismissible BIT NOT NULL,
	Shapeable BIT NOT NULL,
	Verbal BIT NOT NULL,
	Somatic BIT NOT NULL,
	Material BIT NOT NULL,
	Focus BIT NOT NULL,
	DivineFocus BIT NOT NULL,
	Sorcerer INT,
	Wizard INT,
	Cleric INT,
	Druid INT,
	Ranger INT,
	Bard INT,
	Paladin INT,
	Alchemist INT,
	Summoner INT,
	Witch INT,
	Inquisitor INT,
	Oracle INT,
	Antipaladin INT,
	Magus INT,
	Shaman INT,
	Bloodrager INT,
	SlaLevel INT NOT NULL,
	Implemented BIT,
	ShortDescription VARCHAR(200)
	)
