CREATE TABLE [dbo].[WeaponDto] (
	[Id] INT IDENTITY(1, 1) NOT NULL,
	[Name] VARCHAR(255),
	[Description] VARCHAR(50),
	Cost INT NOT NULL,
	WeaponGroup VARCHAR(50),
	DmgS VARCHAR(50),
	MediumDamage VARCHAR(50),
	Threshhold INT NOT NULL,
	Multiplier INT NOT NULL,
	[Range] INT NOT NULL,
	[Weight] INT NOT NULL,
	DamageType VARCHAR(50),
	[Source] VARCHAR(50),
	Category VARCHAR(50),
	ItemType VARCHAR(50),
	[Action] VARCHAR(50),
	[Subtype] VARCHAR(50),
	Misfire INT NOT NULL,
	MisfireRange INT NOT NULL,
	Capacity INT NOT NULL,
	AdvancedFirearm BIT
	)
