CREATE TABLE [dbo].[WordDto] (
	[Id] INT IDENTITY(1, 1) NOT NULL,
	[Name] VARCHAR(255),
	Duration VARCHAR(50),
	School VARCHAR(50),
	Subschool VARCHAR(50),
	WordType VARCHAR(50),
	WordSubtype VARCHAR(50),
	SpellType VARCHAR(50),
	Targets VARCHAR(50),
	[Save] VARCHAR(50),
	Harmless BIT NOT NULL,
	Resistance BIT NOT NULL,
	[Description] VARCHAR(MAX),
	[Boost1] VARCHAR(300),
	[Boost2] VARCHAR(255),
	Alchemist INT NOT NULL,
	Bard INT NOT NULL,
	SorWiz INT NOT NULL,
	Cleric INT NOT NULL,
	Druid INT NOT NULL,
	Inquisitor INT NOT NULL,
	Summoner INT NOT NULL,
	Witch INT NOT NULL,
	Ranger INT NOT NULL,
	Paladin INT NOT NULL,
	Magus INT NOT NULL,
	)
