CREATE TABLE [dbo].[WordDto] (
	[Id] INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
	[Name] VARCHAR(255),
	Duration VARCHAR(50),
	School VARCHAR(50),
	Subschool VARCHAR(50),
	WordType VARCHAR(50),
	WordSubtype VARCHAR(50),
	SpellType VARCHAR(50),
	Targets VARCHAR(50),
	[Save] VARCHAR(50),
	Harmless BIT NOT NULL,
	Resistance BIT  ,
	[Description] VARCHAR(MAX),
	[Boost1] VARCHAR(300),
	[Boost2] VARCHAR(255),
	Alchemist INT NOT NULL,
	Bard INT NOT NULL,
	Sorcerer INT NOT NULL,
	Wizard INT NOT NULL,
	Cleric INT NOT NULL,
	Druid INT NOT NULL,
	Inquisitor INT NOT NULL,
	Summoner INT NOT NULL,
	Witch INT NOT NULL,
	Ranger INT NOT NULL,
	Paladin INT NOT NULL,
	Magus INT NOT NULL,
	[Level] INT NOT NULL,
	[Range] varchar(300),
	[Target] varchar(300),
	[SR] bit NOT NULL
	)
