CREATE TABLE [dbo].[MonsterDto] (
	[Id] INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
	[Name] VARCHAR(255),
	CR VARCHAR(5),
	Race VARCHAR(150),
	Classes VARCHAR(150),
	Alignment VARCHAR(50),
	Size VARCHAR(50),
	[Type] VARCHAR(50),
	SubType VARCHAR(50),
	[Init] INT NOT NULL,
	Senses VARCHAR(150),
	Aura VARCHAR(150),
	ACMods VARCHAR(150),
	HP INT NOT NULL,
	HD VARCHAR(50),
	HPMods VARCHAR(150),
	Fort INT NOT NULL,
	Ref INT NOT NULL,
	Will INT NOT NULL,
	SaveMods VARCHAR(150),
	DefensiveAbilities VARCHAR(150),
	DR VARCHAR(150),
	Immune VARCHAR(250),
	Resist VARCHAR(150),
	SR INT NOT NULL,
	Weaknesses VARCHAR(150),
	Speed VARCHAR(250),
	Speed_Mod VARCHAR(150),
	Melee VARCHAR(450),
	Ranged VARCHAR(150),
	Reach VARCHAR(150),
	SpecialAttacks VARCHAR(Max),
	SpellLikeAbilities VARCHAR(Max),
	SpellsKnown VARCHAR(Max),
	SpellsPrepared VARCHAR(Max),
	SpellDomains VARCHAR(150),
	AbilityScores VARCHAR(50),
	BaseAtk VARCHAR(50),
	Feats VARCHAR(300),
	Skills VARCHAR(300),
	RacialMods VARCHAR(250),
	Languages VARCHAR(250),
	SQ VARCHAR(200),
	Environment VARCHAR(150),
	Organization VARCHAR(Max),
	Treasure VARCHAR(Max),
	Description_Visual VARCHAR(Max),
	[Group] VARCHAR(50),
	[Source] VARCHAR(50),
	SpecialAbilities VARCHAR(Max),
	[Description] VARCHAR(MAX),
	Gear VARCHAR(MAX),
	Fly INT,
	Climb INT,
	Burrow INT,
	Swim INT,
	Land INT,
	DirtySkills INT NOT NULL
	)
